name: flutter_taxi_booking_driver_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^3.1.0
  # Singleton access
  get_it: ^3.1.0
  # Value equality
  equatable: ^1.0.2
  # Remote API
  dio: ^3.0.8
  data_connection_checker: ^0.3.4
  # Local cache
  shared_preferences: 0.5.4+9
  # Use Either
  dartz: ^0.8.9
  # Device info
  device_info: ^0.4.1+4
  # Rating bar
  flutter_rating_bar: ^3.0.1+1
  # Google map
  google_maps_flutter: ^0.5.21+15
  # Draw dotted border
  dotted_border: ^1.0.4
  # Country picker
  country_pickers: ^2.0.0
  # Shimmer
  shimmer: ^1.0.1
  # Hive NoSQL database
  hive: ^1.3.0
  # Permission handler
  permission_handler: ^4.2.0+hotfix.2
  # Geolocator
  geolocator: ^5.2.0
  # Share content
  share: ^0.6.3+5
  # Scrollable bottom sheet
  # scrollable_bottom_sheet: ^0.2.1
  # Native splash screen
  flutter_native_splash: ^0.1.9
  # Chart library
  charts_flutter: ^0.10.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/locale/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: GT-Eesti
        fonts:
          - asset: fonts/GT-Eesti-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
      - family: ViitIcons
        fonts:
          - asset: fonts/ViitIcons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
